### ISSUE TITLE
setSupportActionBar() didnt work if use ATEActivity

### ISSUE THREAD

**Issue by adeldolgov** [afollestad/app-theme-engine#106]
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:198)
                                                                            at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:99)
                                                                            at adeldolgov.sort2folder.MainActivity.onCreate(MainActivity.java:212)

I try setSupportActionBar(toolbar); , but i got this error,btw style of MainActivity contains "item name="android:windowActionBar"false/item"

**Comment by PDDStudio** [comment]
This is mostly an issue related to your theme. Are you sure you've set it up correctly?

**Comment by adeldolgov** [comment]
@PDDStudio Yes, i check my theme a lot of times.
If i use AppCombat instead ATEActivity i dont get this error.
Maybe i have this error because i using Material Drawer library by Mike Penz. Well, i should return to 0.7.7 version of ATE :(

**Comment by PDDStudio** [comment]
@adeldolgov can you post snippets/your source? And which version of the drawer are you using/how did you setup your drawer?

**Comment by adeldolgov** [comment]
@PDDStudio I just try create new project  and setup 1.0.0 ATE. If i get this error again, i tell you about it.
