### ISSUE TITLE
Primary Color Should be Opaque Error??

### ISSUE THREAD

**Issue by MidsizeMango** [afollestad/app-theme-engine#24]
```Gradle
Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:596)
at com.afollestad.appthemeengine.ATE.applyTaskDescription(ATE.java:289)
at com.afollestad.appthemeengine.ATE.preApply(ATE.java:143)
at com.afollestad.appthemeengine.ATEActivity.onCreate(ATEActivi
```

**Comment by afollestad** [comment]
That isn't thrown by my library. It looks like that's a limitation of task description (recents entry) coloring on Android.

**Comment by afollestad** [comment]
As a workaround, I'll have the library remove the alpha (transparency) component when applying task description theming. 

But it's generally uncommon to use transparency for a primary theme color.

**Comment by afollestad** [comment]
Alpha will automatically be stripped from primary theme colors when they are applied to your app's task description. This will be available in the next release.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.6.0

**Comment by MidsizeMango** [comment]
@afollestad Thanks, the update 0.6.0 fixed the issue.
