### ISSUE TITLE
NoSuchMethodError in EdgeGlowUtil

### ISSUE THREAD

**Issue by naman14** [afollestad/app-theme-engine#37]
```java
 java.lang.NoSuchMethodError: android.widget.EdgeEffect.setColor
                                                                  at com.afollestad.appthemeengine.util.EdgeGlowUtil.setEdgeGlowColor(EdgeGlowUtil.java:146)
                                                                  at com.afollestad.appthemeengine.util.EdgeGlowUtil.setEdgeGlowColor(EdgeGlowUtil.java:128)
                                                                  at com.afollestad.appthemeengine.util.EdgeGlowUtil$1.onScrollStateChanged(EdgeGlowUtil.java:110)
```

Happens on recyclerview overscroll on Android 4.2.2

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
