### ISSUE TITLE
Crash when using ATESwitchPreference

### ISSUE THREAD

**Issue by jlelse** [afollestad/app-theme-engine#46]
```gradle
android.view.InflateException: Binary XML file line #2: Error inflating class com.afollestad.appthemeengine.views.ATESwitch
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                  at android.preference.Preference.onCreateView(Preference.java:516)
                                                                  at android.preference.Preference.getView(Preference.java:487)
                                                                  at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
                                                                  at android.widget.AbsListView.obtainView(AbsListView.java:2347)
                                                                  at android.widget.ListView.measureHeightOfChildren(ListView.java:1270)
                                                                  at android.widget.ListView.onMeasure(ListView.java:1182)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                                  at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
                                                                  at android.view.View.measure(View.java:17565)
                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2045)
                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1196)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1409)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
                                                              	at android.view.Choreographe
```
I always get this Exception and I think I did everything like the sample.
I also check the key etc.

**Comment by julian200601** [comment]
@jlelse Could you post the xml?

**Comment by jlelse** [comment]
@julian200601 

```
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <com.afollestad.appthemeengine.prefs.ATEColorPreference
        android:key="primary_color"
        android:persistent="false"
        android:summary="@string/primary_color_summary"
        android:title="@string/primary_color"
        app:ateKey_pref_color="?ate_key" />
    <com.afollestad.appthemeengine.prefs.ATEColorPreference
        android:key="accent_color"
        android:persistent="false"
        android:summary="@string/accent_color_summary"
        android:title="@string/accent_color"
        app:ateKey_pref_color="?ate_key" />
    <com.afollestad.appthemeengine.prefs.ATESwitchPreference
        android:defaultValue="false"
        android:key="location_enabled"
        android:persistent="false"
        android:summary="@string/location_enabled_summary"
        android:title="@string/location_enabled_title"
        app:ateKey_pref_switch="?ate_key" />
    <com.afollestad.appthemeengine.prefs.ATESwitchPreference
        android:defaultValue="false"
        android:key="stop_images"
        android:persistent="false"
        android:summary="@string/stop_images_summary"
        android:title="@string/stop_images_title"
        app:ateKey_pref_switch="?ate_key" />
    <com.afollestad.appthemeengine.prefs.ATESwitchPreference
        android:defaultValue="true"
        android:key="messaging_enabled"
        android:summary="@string/messaging_enabled_summary"
        android:title="@string/messaging_enabled_title"
        app:ateKey_pref_switch="default" />
    <com.afollestad.appthemeengine.prefs.ATEListPreference
        android:defaultValue="45000"
        android:entries="@array/service_update_interval"
        android:entryValues="@array/service_update_interval_values"
        android:key="service_update_interval"
        android:summary="@string/service_update_interval_summary"
        android:title="@string/service_update_interval_title"
        app:ateKey_pref_list="?ate_key" />
</PreferenceScreen>
```

**Comment by jlelse** [comment]
But there seems to be a bug in the layout of the ATE View

**Comment by julian200601** [comment]
@jlelse Why are you using "?ate_key" for all preferences but "default" at the last switch? Do you have configured "default"?

**Comment by jlelse** [comment]
@julian200601 Yes I only used default as key but thanks, I forget to replace i with "?ate_key"

**Comment by afollestad** [comment]
Unfortunately the log isn't enough to know what the cause is

**Comment by afollestad** [comment]
Just looking again at this now. Would you be able to get any further log data? It's very weird that I can't reproduce it.

**Comment by afollestad** [comment]
Since it works fine in the sample, I have a feeling it has something to do with an attribute set in your styles.xml file.

**Comment by jlelse** [comment]
Ok thx I will check again

**Comment by afollestad** [comment]
@jlelse I think someone else had the same issue, but this is a bit more detailed:

https://github.com/afollestad/app-theme-engine/issues/64

**Comment by afollestad** [comment]
@jlelse not sure if you're still trying to implement this library or not after all this time, but I believe I've found a solution in #64 that I'll be attempting to implement.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.7.7

**Comment by jlelse** [comment]
Thanks!

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0

**Comment by jlelse** [comment]
Nice update
