### ISSUE TITLE
Null Pointer Exception TabLayoutProcessor

### ISSUE THREAD

**Issue by Jawnnypoo** [afollestad/app-theme-engine#53]
I got a crash when using the library. I performed no setup and just extended `ATEActivity` in the base class and received the crash, probably to do with the fact that 

```Gradle
FATAL EXCEPTION: main
                                                   Process: com.commit451.gitlab, PID: 12916
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.commit451.gitlab/com.commit451.gitlab.activity.ProjectsActivity}: java.lang.NullPointerException
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NullPointerException
                                                       at com.afollestad.appthemeengine.processors.TabLayoutProcessor.process(TabLayoutProcessor.java:44)
                                                       at com.afollestad.appthemeengine.processors.TabLayoutProcessor.process(TabLayoutProcessor.java:20)
                                                       at com.afollestad.appthemeengine.ATE.apply(ATE.java:73)
                                                       at com.afollestad.appthemeengine.ATE.apply(ATE.java:94)
                                                       at com.afollestad.appthemeengine.ATE.apply(ATE.java:94)
                                                       at com.afollestad.appthemeengine.ATE.apply(ATE.java:94)
                                                       at com.afollestad.appthemeengine.ATE.apply(ATE.java:219)
                                                       at com.afollestad.appthemeengine.ATEActivity.onStart(ATEActivity.java:30)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                       at android.app.Activity.performStart(Activity.java:5241)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
```

This is me using version 0.7.0 so it may no longer be an issue.

**Comment by afollestad** [comment]
If you're using an `AppBarLayout`, the crash would make sense. It should be fixed now for the next release.

**Comment by Jawnnypoo** [comment]
Yes, I was indeed. Nice

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.7.5
