### ISSUE TITLE
Sample crash issue from Google Play report, caused by ATESwitch

### ISSUE THREAD

**Issue by afollestad** [afollestad/app-theme-engine#64]
```Gradle
android.view.InflateException: Binary XML file line #2: Error inflating class com.afollestad.appthemeengine.views.ATESwitch
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at android.preference.Preference.onCreateView(Preference.java:516)
	at android.preference.Preference.getView(Preference.java:487)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
	at android.widget.AbsListView.obtainView(AbsListView.java:2344)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillFromTop(ListView.java:759)
	at android.widget.ListView.layoutChildren(ListView.java:1673)
	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15604)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5253)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 60 more
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ViewParent.requestSendAccessibilityEvent(android.view.View, android.view.accessibility.AccessibilityEvent)' on a null object reference
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5294)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:5275)
	at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:20904)
	at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:20937)
	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:7956)
	at android.widget.TextView.setText(TextView.java:4107)
	at android.widget.TextView.setText(TextView.java:3959)
	at android.widget.TextView.<init>(TextView.java:1350)
	at android.widget.Button.<init>(Button.java:111)
	at android.widget.CompoundButton.<init>(CompoundButton.java:81)
	at android.widget.CompoundButton.<init>(CompoundButton.java:77)
	at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:181)
	at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:167)
	at com.afollestad.appthemeengine.views.ATESwitch.<init>(ATESwitch.java:24)
	... 63 more
```

It happens on 5.0/5.1 devices, including the Moto X, ZenFone 2, and Yureka (whatever that is).

**Comment by afollestad** [comment]
Any idea what would cause this? @plusCubed @AnimbusDev 

I'm gonna look more into it when I'm not at work.

**Comment by AnimbusDev** [comment]
@afollestad a ViewParent is null somewhere.

**Comment by afollestad** [comment]
@AnimbusDev the weird thing is that this code is identical to the sample project in the repo here, and it doesn't crash on my Nexus 5X, Nexus 6P, or Nexus 9. It doesn't crash for you, right?

**Comment by julian200601** [comment]
@afollestad  but yours are running 6.0.x aren't they? It doesn't crash on my GS6 running cm 6.0.1 also... And what the heck is ActionBarOverlayLayout? Never heard of that before...

**Comment by afollestad** [comment]
@julian200601 yeah, they all have 6.0.1 😁

When you use `setSupportActionBar(Toolbar)`, it puts the Toolbar inside that, I believe.

**Comment by afollestad** [comment]
I'll have to look into this more tomorrow, this is kind of a high priority crash.

**Comment by julian200601** [comment]
@afollestad I'll downgrade one of my services to 5.1.1 and look if I get the issue, too.

**Comment by julian200601** [comment]
@afollestad No issue on my LG G Pad 8.3 running latest cm nightly (5.1.1)

**Comment by afollestad** [comment]
Yeah this crash really makes no sense at all

**Comment by afollestad** [comment]
I found the problem: https://github.com/android/platform_frameworks_base/blob/master/core/java/android/view/View.java#L5839

Since we override `isShown()` in `ATESwitch` for recent preference animation workarounds, code gets run that shouldn't (*yet*).

@plusCubed @AnimbusDev

**Comment by afollestad** [comment]
I believe I fixed it.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.7.7
