### ISSUE TITLE
ATE Switch Force Stop on some devices

### ISSUE THREAD

**Issue by MidsizeMango** [afollestad/app-theme-engine#76]
```Gradle
android.view.InflateException: Binary XML file line #2: Error inflating class com.afollestad.appthemeengine.views.ATESwitch
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at android.preference.Preference.onCreateView(Preference.java:516)
	at android.preference.Preference.getView(Preference.java:487)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
	at android.widget.AbsListView.obtainView(AbsListView.java:2347)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillFromTop(ListView.java:759)
	at android.widget.ListView.layoutChildren(ListView.java:1673)
	at android.widget.AbsListView.onLayout(AbsListView.java:2151)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2116)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
```

**Comment by afollestad** [comment]
This has already been fixed in the code.

**Comment by MidsizeMango** [comment]
Okay..I will check it out.Some users are reporting that while going into settings my app force stops.

**Comment by afollestad** [comment]
Yes, the library is being completely re-designed right now but a new release should be ready soon.

**Comment by MidsizeMango** [comment]
I think I am probably using 0.7.0..coz after upgrading.my app is giving error for  ColorChooserDialog class .

**Comment by afollestad** [comment]
Your app needs to include Material Dialogs as a dependency if you use the preference classes or Color Chooser.

https://github.com/afollestad/material-dialogs/

**Comment by MidsizeMango** [comment]
@afollestad I have already added Material Dialogs.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
