### ISSUE TITLE
NullpointerException on application start

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/app-theme-engine#92]
After migrating to v 1.0 (and adjusting the source as mentioned in the documentation) the application crashes immediately on it's start and throws a `NullpointerException` : 

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
                                                                     at com.afollestad.appthemeengine.ATE.getPostInflationToolbar(ATE.java:260)
                                                                     at com.afollestad.appthemeengine.ATE.themeOverflow(ATE.java:270)
                                                                     at com.afollestad.appthemeengine.ATEActivity.onCreateOptionsMenu(ATEActivity.java:48)
                                                                     at android.app.Activity.onCreatePanelMenu(Activity.java:2852)
                                                                     at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:298)
                                                                     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                                     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
                                                                     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                                     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
                                                                     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jlelse** [comment]
I can experience this too when returning to an activity

**Comment by PDDStudio** [comment]
@jlelse are you extending ATEActivity or using the other way to configure ATE? For me it is crashing while extending ATEActivity.

**Comment by jlelse** [comment]
For me with ATEActivity too.

**Comment by PDDStudio** [comment]
Should be fixed now.
