### ISSUE TITLE
Crash pre-Lollipop

### ISSUE THREAD

**Issue by TR4Android** [afollestad/app-theme-engine#94]
@afollestad Have you ever tested this on pre-Lollipop devices? I consistently get the following crash on an emulator running 4.4 Kitkat and your sample application:
```
02-12 10:31:50.412    5211-5211/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.afollestad.appthemeenginesample, PID: 5211
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afollestad.appthemeenginesample/com.afollestad.appthemeenginesample.MainActivity}: java.lang.RuntimeException: Failed to get the value of static field ATTRS_THEME.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Failed to get the value of static field ATTRS_THEME.
            at com.afollestad.appthemeengine.inflation.InflationInterceptor.<init>(InflationInterceptor.java:92)
            at com.afollestad.appthemeengine.util.ATEUtil.setInflaterFactory(ATEUtil.java:198)
            at com.afollestad.appthemeengine.ATE.preApply(ATE.java:110)
            at com.afollestad.appthemeengine.ATEActivity.onCreate(ATEActivity.java:22)
            at com.afollestad.appthemeenginesample.MainActivity.onCreate(MainActivity.java:52)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoSuchFieldException: ATTRS_THEME
            at java.lang.Class.getDeclaredField(Class.java:596)
            at com.afollestad.appthemeengine.inflation.InflationInterceptor.<init>(InflationInterceptor.java:88)
            at com.afollestad.appthemeengine.util.ATEUtil.setInflaterFactory(ATEUtil.java:198)
            at com.afollestad.appthemeengine.ATE.preApply(ATE.java:110)
            at com.afollestad.appthemeengine.ATEActivity.onCreate(ATEActivity.java:22)
            at com.afollestad.appthemeenginesample.MainActivity.onCreate(MainActivity.java:52)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```
Seems like there is no field called `ATTRS_THEME` on those devices.

**Comment by jlelse** [comment]
Same for me here

**Comment by Williaan** [comment]
it's not resolved! Error persists

**Comment by afollestad** [comment]
Feel free to make pull requests.  😛

I don't have a lot of time for side work right now.

**Comment by Williaan** [comment]
oh right, i'm trying resolve right now :)

**Comment by igorviter** [comment]
Same for me too

**Comment by e4basil** [comment]
same issue

**Comment by coolalien01** [comment]
same issue  .....still exist this bug :(
